
-- AERQVON trading + market-data foundation
create table if not exists public.market_candles (
  id bigint generated by default as identity primary key,
  market_type text not null check (market_type in ('spot','margin','futures','perpetual')),
  symbol text not null,
  interval text not null check (interval in ('1m','3m','5m','15m','30m','1h','2h','4h','6h','12h','1d','1w')),
  open_time timestamptz not null,
  close_time timestamptz not null,
  open numeric(38,18) not null check (open >= 0),
  high numeric(38,18) not null check (high >= 0),
  low numeric(38,18) not null check (low >= 0),
  close numeric(38,18) not null check (close >= 0),
  volume numeric(38,18) not null default 0 check (volume >= 0),
  quote_volume numeric(38,18) not null default 0 check (quote_volume >= 0),
  trades bigint not null default 0 check (trades >= 0),
  is_closed boolean not null default true,
  source text not null default 'binance',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (market_type, symbol, interval, open_time)
);

create index if not exists market_candles_lookup_idx
  on public.market_candles (market_type, symbol, interval, open_time desc);

create table if not exists public.market_quotes (
  market_type text not null check (market_type in ('spot','margin','futures','perpetual')),
  symbol text not null,
  last_price numeric(38,18) not null check (last_price >= 0),
  bid_price numeric(38,18),
  ask_price numeric(38,18),
  bid_qty numeric(38,18),
  ask_qty numeric(38,18),
  change_24h numeric(38,18),
  high_24h numeric(38,18),
  low_24h numeric(38,18),
  volume_24h numeric(38,18),
  quote_volume_24h numeric(38,18),
  mark_price numeric(38,18),
  index_price numeric(38,18),
  funding_rate numeric(38,18),
  open_interest numeric(38,18),
  event_time timestamptz,
  updated_at timestamptz not null default now(),
  primary key (market_type, symbol)
);

create table if not exists public.trading_positions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  market_type text not null check (market_type in ('spot','margin','futures','perpetual')),
  symbol text not null,
  side text not null check (side in ('long','short')),
  quantity numeric(38,18) not null check (quantity >= 0),
  entry_price numeric(38,18) not null check (entry_price >= 0),
  mark_price numeric(38,18),
  leverage numeric(20,8) not null default 1 check (leverage > 0),
  margin numeric(38,18) not null default 0 check (margin >= 0),
  liquidation_price numeric(38,18),
  unrealized_pnl numeric(38,18) not null default 0,
  realized_pnl numeric(38,18) not null default 0,
  status text not null default 'open' check (status in ('open','closed','liquidated')),
  opened_at timestamptz not null default now(),
  closed_at timestamptz,
  updated_at timestamptz not null default now()
);

create unique index if not exists trading_positions_open_uq
  on public.trading_positions(user_id, market_type, symbol, side)
  where status = 'open';

create index if not exists trading_positions_user_idx
  on public.trading_positions(user_id, updated_at desc);

create table if not exists public.trading_account_events (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null,
  order_id text,
  trade_id bigint,
  asset_id text,
  amount numeric(38,18),
  balance_after numeric(38,18),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists trading_account_events_user_idx
  on public.trading_account_events(user_id, created_at desc);

create table if not exists public.trading_risk_events (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  order_id text,
  market_type text,
  symbol text,
  event_type text not null,
  severity text not null default 'info' check (severity in ('info','warning','critical')),
  message text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists trading_risk_events_user_idx
  on public.trading_risk_events(user_id, created_at desc);

alter table public.trading_orders
  add column if not exists client_order_id text,
  add column if not exists market_type text not null default 'spot',
  add column if not exists time_in_force text,
  add column if not exists reduce_only boolean not null default false,
  add column if not exists leverage numeric(20,8),
  add column if not exists exchange_order_id text,
  add column if not exists exchange text,
  add column if not exists idempotency_key uuid;

create unique index if not exists trading_orders_user_client_order_uq
  on public.trading_orders(user_id, client_order_id)
  where client_order_id is not null;

create unique index if not exists trading_orders_user_idempotency_uq
  on public.trading_orders(user_id, idempotency_key)
  where idempotency_key is not null;

create index if not exists trading_orders_user_status_idx
  on public.trading_orders(user_id, status, created_at desc);

alter table public.market_candles enable row level security;
alter table public.market_quotes enable row level security;
alter table public.trading_positions enable row level security;
alter table public.trading_account_events enable row level security;
alter table public.trading_risk_events enable row level security;

drop policy if exists market_candles_public_read on public.market_candles;
create policy market_candles_public_read on public.market_candles
  for select to anon, authenticated using (true);

drop policy if exists market_quotes_public_read on public.market_quotes;
create policy market_quotes_public_read on public.market_quotes
  for select to anon, authenticated using (true);

drop policy if exists trading_positions_select_own on public.trading_positions;
create policy trading_positions_select_own on public.trading_positions
  for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists trading_account_events_select_own on public.trading_account_events;
create policy trading_account_events_select_own on public.trading_account_events
  for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists trading_risk_events_select_own on public.trading_risk_events;
create policy trading_risk_events_select_own on public.trading_risk_events
  for select to authenticated using ((select auth.uid()) = user_id);

-- Market tables are server-written only.
revoke insert, update, delete on public.market_candles from anon, authenticated;
revoke insert, update, delete on public.market_quotes from anon, authenticated;

-- Account/position/risk tables are server-written only.
revoke insert, update, delete on public.trading_positions from anon, authenticated;
revoke insert, update, delete on public.trading_account_events from anon, authenticated;
revoke insert, update, delete on public.trading_risk_events from anon, authenticated;

-- Trading state is server-authoritative; clients may read their own records.
revoke insert, update, delete on public.trading_balances from authenticated, anon;
revoke insert, update, delete on public.trading_orders from authenticated, anon;
revoke insert, update, delete on public.trading_trades from authenticated, anon;
revoke insert, update, delete on public.trading_notifications from authenticated, anon;

-- Ensure Realtime can publish server-side state changes.
do $$
begin
  begin
    alter publication supabase_realtime add table public.market_quotes;
  exception when duplicate_object then null;
  end;
  begin
    alter publication supabase_realtime add table public.trading_orders;
  exception when duplicate_object then null;
  end;
  begin
    alter publication supabase_realtime add table public.trading_trades;
  exception when duplicate_object then null;
  end;
  begin
    alter publication supabase_realtime add table public.trading_balances;
  exception when duplicate_object then null;
  end;
  begin
    alter publication supabase_realtime add table public.trading_positions;
  exception when duplicate_object then null;
  end;
  begin
    alter publication supabase_realtime add table public.trading_notifications;
  exception when duplicate_object then null;
  end;
end $$;

-- Protect the transfer RPC while retaining authenticated access.
revoke execute on function public.transfer_tokens_by_aqv_id(text,text,numeric,uuid,text) from public, anon;
grant execute on function public.transfer_tokens_by_aqv_id(text,text,numeric,uuid,text) to authenticated;
;
