-- Reconciled from the live AERQVON Supabase project.
-- This migration captures the live-market and server-authoritative trading foundation.

create table if not exists public.market_candles (
  id bigint generated by default as identity primary key,
  market_type text not null check (market_type in ('spot','margin','futures','perpetual')),
  symbol text not null,
  interval text not null check (interval in ('1m','3m','5m','15m','30m','1h','2h','4h','6h','12h','1d','1w')),
  open_time timestamptz not null,
  close_time timestamptz not null,
  open numeric(38,18) not null,
  high numeric(38,18) not null,
  low numeric(38,18) not null,
  close numeric(38,18) not null,
  volume numeric(38,18) not null default 0,
  quote_volume numeric(38,18) not null default 0,
  trades bigint not null default 0,
  is_closed boolean not null default false,
  source text not null default 'binance',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (market_type,symbol,interval,open_time)
);

create index if not exists market_candles_lookup_idx on public.market_candles(market_type,symbol,interval,open_time desc);

create table if not exists public.market_quotes (
  market_type text not null check (market_type in ('spot','margin','futures','perpetual')),
  symbol text not null,
  last_price numeric(38,18),
  bid_price numeric(38,18),
  bid_quantity numeric(38,18),
  ask_price numeric(38,18),
  ask_quantity numeric(38,18),
  change_24h numeric(38,18),
  high_24h numeric(38,18),
  low_24h numeric(38,18),
  volume_24h numeric(38,18),
  quote_volume_24h numeric(38,18),
  mark_price numeric(38,18),
  index_price numeric(38,18),
  funding_rate numeric(38,18),
  open_interest numeric(38,18),
  event_time timestamptz,
  updated_at timestamptz not null default now(),
  primary key (market_type,symbol)
);

create table if not exists public.trading_positions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  market_type text not null check (market_type in ('spot','margin','futures','perpetual')),
  symbol text not null,
  side text not null check (side in ('long','short')),
  quantity numeric(38,18) not null default 0,
  entry_price numeric(38,18) not null default 0,
  mark_price numeric(38,18) not null default 0,
  leverage numeric(20,8) not null default 1,
  margin numeric(38,18) not null default 0,
  liquidation_price numeric(38,18),
  unrealized_pnl numeric(38,18) not null default 0,
  realized_pnl numeric(38,18) not null default 0,
  status text not null default 'open' check (status in ('open','closed','liquidated')),
  opened_at timestamptz not null default now(),
  closed_at timestamptz,
  updated_at timestamptz not null default now()
);

create unique index if not exists trading_positions_open_unique
on public.trading_positions(user_id,market_type,symbol,side)
where status='open';

create table if not exists public.trading_account_events (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null,
  order_id uuid,
  trade_id uuid,
  asset_id text,
  amount numeric(38,18),
  balance_after numeric(38,18),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists trading_account_events_user_idx on public.trading_account_events(user_id,created_at desc);

create table if not exists public.trading_risk_events (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  order_id uuid,
  market_type text,
  symbol text,
  event_type text not null,
  severity text not null default 'info' check (severity in ('info','warning','critical')),
  message text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists trading_risk_events_user_idx on public.trading_risk_events(user_id,created_at desc);

alter table public.trading_orders
  add column if not exists client_order_id text,
  add column if not exists market_type text not null default 'spot',
  add column if not exists time_in_force text,
  add column if not exists reduce_only boolean not null default false,
  add column if not exists leverage numeric(20,8),
  add column if not exists exchange_order_id text,
  add column if not exists exchange text,
  add column if not exists idempotency_key uuid;

create unique index if not exists trading_orders_client_order_unique on public.trading_orders(user_id,client_order_id) where client_order_id is not null;
create unique index if not exists trading_orders_idempotency_unique on public.trading_orders(user_id,idempotency_key) where idempotency_key is not null;
create index if not exists trading_orders_status_created_idx on public.trading_orders(user_id,status,created_at desc);

alter table public.market_candles enable row level security;
alter table public.market_quotes enable row level security;
alter table public.trading_positions enable row level security;
alter table public.trading_account_events enable row level security;
alter table public.trading_risk_events enable row level security;

revoke all on public.market_candles,public.market_quotes from anon,authenticated;
grant select on public.market_candles,public.market_quotes to anon,authenticated;

drop policy if exists "Public can read market candles" on public.market_candles;
create policy "Public can read market candles" on public.market_candles for select to anon,authenticated using (true);
drop policy if exists "Public can read market quotes" on public.market_quotes;
create policy "Public can read market quotes" on public.market_quotes for select to anon,authenticated using (true);

revoke all on public.trading_positions,public.trading_account_events,public.trading_risk_events from anon,authenticated;
grant select on public.trading_positions,public.trading_account_events,public.trading_risk_events to authenticated;

drop policy if exists "Users can view their trading positions" on public.trading_positions;
create policy "Users can view their trading positions" on public.trading_positions for select to authenticated using ((select auth.uid())=user_id);
drop policy if exists "Users can view their account events" on public.trading_account_events;
create policy "Users can view their account events" on public.trading_account_events for select to authenticated using ((select auth.uid())=user_id);
drop policy if exists "Users can view their risk events" on public.trading_risk_events;
create policy "Users can view their risk events" on public.trading_risk_events for select to authenticated using ((select auth.uid())=user_id);

revoke insert,update,delete on public.trading_balances,public.trading_orders,public.trading_trades,public.trading_notifications from anon,authenticated;
